# Description: Update ADSS Rules using GitHub Actions
#
# This is free software, licensed under the GPL v3 License.
# See /LICENSE for more information.

name: Update Rules

env:
  TZ: Asia/Shanghai

on:
  workflow_dispatch:
  schedule:
    - cron: 8 16 * * *

jobs:
  Update:
    name: Update Rules
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: write

    steps:
    
      - name: CheckOut
        uses: actions/checkout@v7

      - name: Set TimeZone
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo timedatectl set-timezone "$TZ"
      
      - name: Build Rules
        shell: sh
        run: |
          chmod +x ./rules/builder/build.sh
          ./rules/builder/build.sh

      - name: Commit and Push Rules
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_author: Clion <clion007@126.com>
          commit_message: Automated Update Rules
          file_pattern: rules/file/*.conf
      
      - name: Delete Workflow Runs
        uses: Mattraks/delete-workflow-runs@main
        continue-on-error: true
        with:
          retain_days: 0
          keep_minimum_runs: 2
